# Generated by Django 5.1.3 on 2025-01-04 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungryhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('categoria', models.CharField(choices=[('FF', 'Fast Food'), ('PZ', 'Pizzaria'), ('RT', 'Restaurante'), ('CF', 'Cafeteria'), ('PD', 'Padaria')], default='RT', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('hungryhub.usuario',),
        ),
    ]
