# Generated by Django 5.1.3 on 2025-01-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungryhub', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.TextField(max_length=50)),
                ('estado', models.TextField(max_length=50)),
                ('rua', models.TextField(max_length=100)),
                ('cep', models.TextField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hungryhub.cliente', to_field='cpf')),
            ],
        ),
    ]
