# Generated by Django 5.1.3 on 2025-01-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hungryhub', '0002_loja'),
        ('hungryhub', '0003_produto'),
    ]

    operations = [
    ]
