# Generated by Django 5.1.3 on 2025-01-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hungryhub', '0002_cliente'),
        ('hungryhub', '0003_create_groups'),
    ]

    operations = [
    ]
