# Generated by Django 5.1.3 on 2025-01-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungryhub', '0004_merge_0002_loja_0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hungryhub.loja'),
            preserve_default=False,
        ),
    ]
